// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js/greeter/greeter.js', ['rf.greeter'], ['goog.dom', 'rf.greeter.greeting'], false);
goog.addDependency('../../../../src/js/greeter/greeting.js', ['rf.greeter.greeting'], [], false);
