// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js/weather/model/weather_model.js', ['rf.weather.model.WeatherModel'], ['goog.dom', 'goog.events.EventTarget'], false);
goog.addDependency('../../../../src/js/weather/presenter/weather_presenter.js', ['rf.weather.presenter.WeatherPresenter'], ['goog.events', 'rf.weather.model.WeatherModel', 'rf.weather.service.StorageService', 'rf.weather.service.WeatherService', 'rf.weather.view.WeatherView'], false);
goog.addDependency('../../../../src/js/weather/service/storage_service.js', ['rf.weather.service.StorageService'], ['goog.storage.Storage', 'goog.storage.mechanism.mechanismfactory'], false);
goog.addDependency('../../../../src/js/weather/service/weather_service.js', ['rf.weather.service.WeatherService'], ['goog.Uri', 'goog.events', 'goog.net.XhrIo'], false);
goog.addDependency('../../../../src/js/weather/view/weather_view.js', ['rf.weather.view.WeatherView'], ['goog.dom', 'goog.events.KeyHandler', 'goog.ui.Component'], false);
goog.addDependency('../../../../src/js/weather/weather.js', ['rf.weather'], ['rf.weather.model.WeatherModel', 'rf.weather.presenter.WeatherPresenter', 'rf.weather.view.WeatherView'], false);
