// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js/passgen/passgen.js', ['rf.passgen'], ['rf.passgen.view.PassgenView'], false);
goog.addDependency('../../../../src/js/passgen/view/passgen_view.js', ['rf.passgen.view.PassgenView'], ['goog.events', 'goog.ui.Component', 'goog.ui.Control'], false);
